theme: minima
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Analyzing Power Outages in United States
description: > # this means to ignore newlines until "baseurl:"
  Built for DSC 80 @ UCSD.

author:
  robert_rawlins:
      name: Robert Rawlins
      email: robert@sorryapp.com
      web: http://twitter.com/sirrawlins
  robin_geall:
      name: Robin Geall
      email: robin@sorryapp.com
      web: http://twitter.com/robingeall